#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

# The key lives in Pendia's database, not in .env, so nothing is read from or
# written to an env file.
ENV_FILE="$(mktemp -u)"

for tool in curl jq; do
  command -v "$tool" >/dev/null 2>&1 || { printf '%s is required.\n' "$tool"; exit 1; }
done

# Secrets go through files in a private directory, never through argv.
WORK="$(mktemp -d)"
chmod 700 "$WORK"
trap 'rm -rf "$WORK"' EXIT

# api METHOD PATH [BODY_FILE] calls Pendia with the session token and prints
# the HTTP status; the response body lands in $WORK/body.
api() {
  local args=(-sS -o "$WORK/body" -w '%{http_code}' -X "$1" -H "@$WORK/auth")
  [[ -n "${3:-}" ]] && args+=(-H "content-type: application/json" --data-binary "@$3")
  curl "${args[@]}" "$PENDIA_URL$2" || true
}

banner "Pendia: TMDB metadata"

# ── 1. TMDB API key ────────────────────────────────────────────────────────
stage "TMDB: copy your API key"
say "Pendia uses TMDB's short v3 API key, not the long Read Access Token."
open_url "https://www.themoviedb.org/settings/api"
step "Sign in to TMDB if it asks."
step "Under 'API Key', copy the 32-character value."
note "Skip 'API Read Access Token' (the long one starting eyJ). Pendia doesn't use it."
while true; do
  ask_secret TMDB_API_KEY "Paste the API key:"
  TMDB_API_KEY="${TMDB_API_KEY//[[:space:]]/}"
  # curl reads the URL from stdin, so the key never shows in the process list.
  status=$(printf 'url = "https://api.themoviedb.org/3/configuration?api_key=%s"\n' "$TMDB_API_KEY" \
    | curl -sS -o /dev/null -w '%{http_code}' -K - || true)
  if [[ "$status" == 200 ]]; then
    printf '  %s✓ TMDB accepted the key%s\n' "$GREEN" "$RESET"
    break
  fi
  warn "TMDB answered $status. Copy the API key, not the token, and paste it again."
done
pause "Press Enter to continue."

# ── 2. Sign in to Pendia ───────────────────────────────────────────────────
stage "Pendia: sign in as an admin"
say "The wizard signs in with your admin account to store the key."
ask PENDIA_URL "Pendia address [http://localhost:3000]:"
PENDIA_URL="${PENDIA_URL:-http://localhost:3000}"
PENDIA_URL="${PENDIA_URL%/}"
until [[ "$(curl -sS -o /dev/null -w '%{http_code}' "$PENDIA_URL/readyz" 2>/dev/null || true)" == 200 ]]; do
  warn "$PENDIA_URL/readyz isn't answering ready yet."
  pause "Start Pendia, then press Enter to try again."
done
ask PENDIA_USER "Admin username:"
while true; do
  ask_secret PENDIA_PASSWORD "Password:"
  PENDIA_USER="$PENDIA_USER" PENDIA_PASSWORD="$PENDIA_PASSWORD" \
    DEVICE_ID="tmdb-wizard-$$" DEVICE_NAME="$(hostname)" \
    jq -n '{username: env.PENDIA_USER, password: env.PENDIA_PASSWORD,
            clientName: "Pendia TMDB wizard", deviceId: env.DEVICE_ID,
            deviceName: env.DEVICE_NAME}' > "$WORK/login.json"
  status=$(curl -sS -o "$WORK/body" -w '%{http_code}' -H "content-type: application/json" \
    --data-binary "@$WORK/login.json" "$PENDIA_URL/api/auth/login" || true)
  rm -f "$WORK/login.json"
  if [[ "$status" == 200 ]] && jq -e '.token' "$WORK/body" >/dev/null 2>&1; then
    printf 'Authorization: Bearer %s\n' "$(jq -r '.token' "$WORK/body")" > "$WORK/auth"
    printf '  %s✓ signed in as %s%s\n' "$GREEN" "$PENDIA_USER" "$RESET"
    break
  fi
  warn "Sign-in failed with $status. Check the password and try again."
done
pause "Press Enter to continue."

# ── 3. Store the key ───────────────────────────────────────────────────────
stage "Pendia: store the TMDB key"
TMDB_API_KEY="$TMDB_API_KEY" jq -n '{value: env.TMDB_API_KEY}' > "$WORK/key.json"
status=$(api PUT /api/settings/providers/tmdb "$WORK/key.json")
rm -f "$WORK/key.json"
if [[ "$status" == 200 ]] && jq -e '.providerKeys | index("tmdb")' "$WORK/body" >/dev/null 2>&1; then
  printf '  %s✓ stored the TMDB key in Pendia%s\n' "$GREEN" "$RESET"
  note "Pendia never shows the key again; settings only list that 'tmdb' is set."
else
  warn "Pendia answered $status: $(jq -c '.error // .' "$WORK/body" 2>/dev/null)"
  note "A 403 means this account lacks the manage-server permission."
  exit 1
fi
pause "Press Enter to continue."

# ── 4. Rescan movies ───────────────────────────────────────────────────────
stage "Pendia: rescan movies"
say "Movies scanned before the key wait as pending. A scan fetches their metadata and posters."
status=$(api GET /api/libraries)
movies=()
if [[ "$status" == 200 ]]; then
  mapfile -t movies < <(jq -r '.[] | select(.medium == "movies") | "\(.id)\t\(.name)"' "$WORK/body")
else
  warn "Couldn't list libraries ($status)."
fi
if (( ${#movies[@]} == 0 )); then
  note "No movies library yet. Add one in the admin UI; its first scan uses the key."
fi
printf '{}' > "$WORK/empty.json"
for entry in "${movies[@]}"; do
  id="${entry%%$'\t'*}"
  name="${entry#*$'\t'}"
  if confirm "Scan '$name' now?"; then
    status=$(api POST "/api/libraries/$id/scan" "$WORK/empty.json")
    if [[ "$status" == 200 ]]; then
      printf '  %s✓ scan queued for %s%s\n' "$GREEN" "$name" "$RESET"
    else
      warn "Scan of '$name' answered $status."
      SKIPPED+=("scan the '$name' library from the admin UI")
    fi
  fi
done
api POST /api/auth/logout >/dev/null
# ──────────────────────────────────────────────────────────────────────────

finish
note "Posters appear as each movie's metadata job finishes."
note "A movie still unmatched after the scan needs a {tmdb-…} or {imdb-…} tag in its folder name."
printf '\n'
